
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TD = 46;
  public static final int H6 = 85;
  public static final int H5 = 83;
  public static final int H4 = 81;
  public static final int H3 = 79;
  public static final int H2 = 77;
  public static final int EOBJECT = 17;
  public static final int FRAME = 30;
  public static final int H1 = 75;
  public static final int ESUB = 68;
  public static final int PARAM = 18;
  public static final int TABLE = 40;
  public static final int ELI = 58;
  public static final int EVAR = 24;
  public static final int ESELECT = 37;
  public static final int SUP = 69;
  public static final int EFONT = 72;
  public static final int FONT = 71;
  public static final int SUB = 67;
  public static final int FRAMESET = 27;
  public static final int LI = 57;
  public static final int CENTER = 73;
  public static final int EBUTTON = 5;
  public static final int TEXT = 29;
  public static final int OBJECT = 16;
  public static final int EHTML = 3;
  public static final int HTML = 2;
  public static final int EU = 64;
  public static final int EDIV = 9;
  public static final int EP = 88;
  public static final int EDIR = 7;
  public static final int EI = 62;
  public static final int EMAP = 13;
  public static final int SELECT = 36;
  public static final int ESMALL = 66;
  public static final int EB = 60;
  public static final int EA = 52;
  public static final int ESCRIPT = 20;
  public static final int NOFRAMES = 31;
  public static final int INPUT = 35;
  public static final int ELABEL = 11;
  public static final int U = 63;
  public static final int DIV = 8;
  public static final int P = 87;
  public static final int ETITLE = 23;
  public static final int EFRAMESET = 28;
  public static final int DIR = 6;
  public static final int SMALL = 65;
  public static final int EOL = 56;
  public static final int MAP = 12;
  public static final int I = 61;
  public static final int EPRE = 19;
  public static final int EOPTION = 39;
  public static final int EFORM = 34;
  public static final int EUL = 54;
  public static final int FORM = 33;
  public static final int EOF = 0;
  public static final int B = 59;
  public static final int A = 51;
  public static final int BUTTON = 4;
  public static final int ESPAN = 22;
  public static final int SPAN = 21;
  public static final int LABEL = 10;
  public static final int EBODY = 26;
  public static final int EMENU = 15;
  public static final int BODY = 25;
  public static final int MENU = 14;
  public static final int error = 1;
  public static final int ETR = 43;
  public static final int OL = 55;
  public static final int UL = 53;
  public static final int ENOFRAMES = 32;
  public static final int ETH = 45;
  public static final int IMG = 50;
  public static final int ETD = 47;
  public static final int BR = 90;
  public static final int EH6 = 86;
  public static final int EH5 = 84;
  public static final int EH4 = 82;
  public static final int EH3 = 80;
  public static final int HR = 89;
  public static final int EH2 = 78;
  public static final int EH1 = 76;
  public static final int OPTION = 38;
  public static final int TBODY = 49;
  public static final int ECENTER = 74;
  public static final int TR = 42;
  public static final int ETABLE = 41;
  public static final int THEAD = 48;
  public static final int ESUP = 70;
  public static final int TH = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HTML",
  "EHTML",
  "BUTTON",
  "EBUTTON",
  "DIR",
  "EDIR",
  "DIV",
  "EDIV",
  "LABEL",
  "ELABEL",
  "MAP",
  "EMAP",
  "MENU",
  "EMENU",
  "OBJECT",
  "EOBJECT",
  "PARAM",
  "EPRE",
  "ESCRIPT",
  "SPAN",
  "ESPAN",
  "ETITLE",
  "EVAR",
  "BODY",
  "EBODY",
  "FRAMESET",
  "EFRAMESET",
  "TEXT",
  "FRAME",
  "NOFRAMES",
  "ENOFRAMES",
  "FORM",
  "EFORM",
  "INPUT",
  "SELECT",
  "ESELECT",
  "OPTION",
  "EOPTION",
  "TABLE",
  "ETABLE",
  "TR",
  "ETR",
  "TH",
  "ETH",
  "TD",
  "ETD",
  "THEAD",
  "TBODY",
  "IMG",
  "A",
  "EA",
  "UL",
  "EUL",
  "OL",
  "EOL",
  "LI",
  "ELI",
  "B",
  "EB",
  "I",
  "EI",
  "U",
  "EU",
  "SMALL",
  "ESMALL",
  "SUB",
  "ESUB",
  "SUP",
  "ESUP",
  "FONT",
  "EFONT",
  "CENTER",
  "ECENTER",
  "H1",
  "EH1",
  "H2",
  "EH2",
  "H3",
  "EH3",
  "H4",
  "EH4",
  "H5",
  "EH5",
  "H6",
  "EH6",
  "P",
  "EP",
  "HR",
  "BR"
  };
}

